export const CONTENT_CODES = {
  ABOUT_US: "about_us",
  ADDRESS: "address",
  ANNOUNCE_CUSTOMERS_REGISTER_REQUIRE: "announce_customers_register_require",
  ANNOUNCEMENT: "announcement",
  BANNER: "banner",
  C_ORDER: "c_order",
  C_ORDER_NOTE: "c_order_note",
  CHECKOUT: "checkout",
  CONFIRM_EDIT_ORDER: "confirm_edit_order",
  CONTACT_CONTENT: "contact_content",
  CONTACT_INFO: "contact_info",
  CONTEN_CUSTOMERS_FORGET_PASSWORD: "conten_customers_forget_password",
  CONTEN_CUSTOMERS_REGISTER_REQUIRE: "conten_customers_register_require",
  CUSTOMER_REGULATIONS: "customer_regulations",
  DISABLE_WEBSITE: "disable_website",
  GUIDE: "guide",
  HELP_NOTE: "help_note",
  INCLUDE_NOTE: "include_note",
  INCLUDE_WARN: "include_warn",
  KEYWORD: "keyword",
  LOGO_BANKS: "logo_banks",
  META: "meta",
  ORDER_EMAIL: "order_email",
  ORDER_EMAIL2: "order_email2",
  ORDER_NOTE: "order_note",
  ORDER_OVER_NOTE: "order_over_note",
  PAYMENT_NOTE: "payment_note",
  QUOTATION_EMAIL: "quotation_email",
  RECRUITMENT: "recruitment",
  RESELLER: "reseller",
  SERVICE: "service",
  SORT_INTRO: "sort_intro",
  TITLE: "title",
} as const;

export type ContentCode = (typeof CONTENT_CODES)[keyof typeof CONTENT_CODES];
